name: pbl_kompen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  bitsdojo_window: ^0.1.6
  grouped_list: ^6.0.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  feather_icons: ^1.2.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  file_picker: ^5.2.0
  font_awesome_flutter: ^10.0.0
  pdf: ^3.11.0
  printing: ^5.9.0
  http: ^1.2.2
  flutter_secure_storage: ^9.0.0
  intl: ">=0.16.0 <0.18.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/profile.png
    - assets/images/qr_code.png
    - assets/images/Logo-polinema.png